### ISSUE TITLE
Filter submission display

### ISSUE THREAD

**Issue by kjohnson** [kjohnson/ninja-forms-videomail#1]
Filter the submission display with a preview and download link for the video.

Submitted Values
- [x] Preview Link

Metabox
- [x] Video Embed
- [x] Download Link (video/webm)
- [x] Download Link (video/mp4)

**Comment by kjohnson** [comment]
<img width="1280" alt="screenshot 2016-06-10 22 00 19" src="https://cloud.githubusercontent.com/assets/10858303/15982485/09a2cff2-2f57-11e6-8978-539e72dd2c3e.png">

**Comment by binarykitchen** [comment]
wohoo, looks great :)

just one thing about the download webm link ... you know there is also an url to download the mp4 file for maximum browser compatibility. but it is not immediately available because the server is encoding it after the POST request (because i dont want the user to wait too long)

so, before you display the videomail message, i recommend to do a GET request to fetch the latest videomail data which will have the link to the mp4 file. and then display the video accordingly with two download links (webm + mp4)

**Comment by kjohnson** [comment]
Ok,  I was checking for an mp4 on the front end, but wasn't seeing anything come through.

**Comment by binarykitchen** [comment]
hmm, then it is a bug or something done wrong. tell me, how and where did you check?

if you use this API call `videomail.get(key, cb)` then it should give you a json that has a link to the mp4 as well: https://github.com/binarykitchen/videomail-client#get

**Comment by kjohnson** [comment]
I'm using `videomail[ 'mp4' ]` in the `SUBMITTED` event.
https://github.com/kjohnson/ninja-forms-videomail/blob/master/assets/js/videomail.js#L31

**Comment by binarykitchen** [comment]
that's correct behaviour. because the mp4 video file is NOT immediately available upon POST (= submit). because the ffmpeg encoder on the server side hasn't completed the job. it takes 20 sec to 2 mins to encode the optimised mp4 video (depending on duration and fps).

hence i recommend to use `videomail.get(key, cb)` each time before you display a video or its details anywhere on wordpress. only save the key (ID) but nothing else. don't cache anything. this to make sure all is always in sync and clients always have the latest data.

**Comment by binarykitchen** [comment]
to help to understand how the controller works on server side, here an extract of the protected node.js code:

```js
exports.post = function(req, res, next) {

    const isVideomailSite = req.siteName === 'videomail.io'

    var videomail

    async.series({

        checkKey: function(cb) {
            if (!req.body.key || req.body.key == 'undefined') {

                const err = new UnprocessableError('Validation for videomail failed')
                err.setDetail('key', 'Key is missing')

                cb(err)
            } else
                cb()
        },

        save: function(cb) {
            videomail = Videomail.create(req.siteName, req.body.key, req.body)

            if (videomail.isEmail()) {
                videomail.set('sending', true)
            }

            videomail.post(cb)
        },

        copyPreview: function(cb) {
            videomail.copyPreview(cb)
        },

        snapshot: function(cb) {
            videomail.getSnapshot(cb)
        },

        reportUrl: function(cb) {
            if (isVideomailSite) {
                videomail.getReportUrl(true, cb)
            } else {
                cb()
            }
        }

    }, function(err, results) {

        if (err) {
            next(err)
        } else {
            const data = {}

            if (isVideomailSite && results.reportUrl) {
                data.nextUrl = results.reportUrl
            }

            data.videomail = results.snapshot

            res.json(data)

            // encode and send, the real hard work starts here!
            videomail.finalize(function(err) {
                if (err) {
                    next(err)
                }
            })
        }
    })
}
```

as you can see, the finalize() call is executed AFTER `res.json()` - because i don't want the user to wait minutes. during these minutes the user will still see the preview video until ffmpeg is complete. works well like that. hope this helps?

**Comment by kjohnson** [comment]
@binarykitchen it looks like the video download types are served from the same URL structure:

`https://videomail.io/videomail/{key}`
`https://videomail.io/videomail/{key}/type/webm`
`https://videomail.io/videomail/{key}/type/mp4`

Would it make sense to just store the video `key` and generate these URLs in the submission area?

**Comment by binarykitchen** [comment]
@kjohnson yes, it is always this structure. correct.

but not sure if generating these urls in the submission area is a good idea. but for now, to make things easier, give it a try.

but if this causes problems, we can improve in a future version, aye?

(i am just a bit worried about stability. what if these server-side generated urls change one day? and what if ffmpeg encoding for mp4 fails for whatever reason? in general it is bad if clients create their own urls against the server (goes agains the concept of hypermedia) but we can ignore that for now. just add a todo remark in the code for now)

**Comment by kjohnson** [comment]
I can agree with that.

For now, I'll patch the `mp4` download link using the URL structure, but we can change that later.
